In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("metrics_doorkey.csv")
df

      method_cls method_name  grid_seed  reward  done
0       baseline      random          0     0.0     0
1       baseline      random          1     0.0     0
2       baseline      random          2     0.0     0
3       baseline      random          3     0.0     0
4       baseline      random          4     0.0     0
...          ...         ...        ...     ...   ...
19995  iterative    gpt_4o_b        995     0.0     0
19996  iterative    gpt_4o_b        996     0.0     0
19997  iterative    gpt_4o_b        997     0.0     0
19998  iterative    gpt_4o_b        998     0.0     0
19999  iterative    gpt_4o_b        999     0.0     0

[20000 rows x 5 columns]

In [12]:
df.groupby('method_name')['reward'].describe()[['mean', 'std']].round(2)

                 mean   std
method_name
claude           0.75  0.41
claude_b         0.88  0.28
claude_c         0.88  0.28
deepseek         0.92  0.23
deepseek_b       0.83  0.35
gemini_25_pro    0.71  0.43
gemini_25_pro_b  0.81  0.36
gemini_25_pro_c  0.90  0.26
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           0.98  0.00
o1               0.97  0.00
o1_b             0.97  0.00
o1_c             0.00  0.00
o3_mini          0.78  0.39
o3_mini_b        0.89  0.27
o3_mini_c        0.98  0.00
o3_mini_d        0.98  0.00
random           0.00  0.00

In [13]:
grouped = df.groupby('method_name')['reward'].agg(['mean', 'std', 'count'])
grouped['ci95'] = 1.96 * grouped['std'] / np.sqrt(grouped['count'])
grouped[['mean', 'ci95']].round(2)

                 mean  ci95
method_name
claude           0.75  0.03
claude_b         0.88  0.02
claude_c         0.88  0.02
deepseek         0.92  0.01
deepseek_b       0.83  0.02
gemini_25_pro    0.71  0.03
gemini_25_pro_b  0.81  0.02
gemini_25_pro_c  0.90  0.02
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           0.98  0.00
o1               0.97  0.00
o1_b             0.97  0.00
o1_c             0.00  0.00
o3_mini          0.78  0.02
o3_mini_b        0.89  0.02
o3_mini_c        0.98  0.00
o3_mini_d        0.98  0.00
random           0.00  0.00

In [14]:
df.groupby('method_name')['done'].describe()[['mean', 'std']].round(2)

                 mean   std
method_name
claude           0.78  0.42
claude_b         0.91  0.29
claude_c         0.91  0.29
deepseek         0.94  0.23
deepseek_b       0.85  0.36
gemini_25_pro    0.73  0.44
gemini_25_pro_b  0.83  0.37
gemini_25_pro_c  0.92  0.27
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           1.00  0.00
o1               1.00  0.00
o1_b             1.00  0.00
o1_c             0.00  0.00
o3_mini          0.80  0.40
o3_mini_b        0.92  0.28
o3_mini_c        1.00  0.00
o3_mini_d        1.00  0.00
random           0.00  0.00

In [15]:
grouped = df.groupby('method_name')['done'].agg(['mean', 'std', 'count'])
grouped['ci95'] = 1.96 * grouped['std'] / np.sqrt(grouped['count'])
grouped[['mean', 'ci95']].round(2)

                 mean  ci95
method_name
claude           0.78  0.03
claude_b         0.91  0.02
claude_c         0.91  0.02
deepseek         0.94  0.01
deepseek_b       0.85  0.02
gemini_25_pro    0.73  0.03
gemini_25_pro_b  0.83  0.02
gemini_25_pro_c  0.92  0.02
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           1.00  0.00
o1               1.00  0.00
o1_b             1.00  0.00
o1_c             0.00  0.00
o3_mini          0.80  0.02
o3_mini_b        0.92  0.02
o3_mini_c        1.00  0.00
o3_mini_d        1.00  0.00
random           0.00  0.00

In [16]:
df[df.grid_seed < 100].groupby('method_name')['reward'].describe()[['mean', 'std']].round(2)

                 mean   std
method_name
claude           0.78  0.39
claude_b         0.91  0.25
claude_c         0.91  0.25
deepseek         0.94  0.19
deepseek_b       0.87  0.31
gemini_25_pro    0.68  0.45
gemini_25_pro_b  0.79  0.38
gemini_25_pro_c  0.91  0.25
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           0.98  0.01
o1               0.97  0.01
o1_b             0.97  0.01
o1_c             0.00  0.00
o3_mini          0.78  0.39
o3_mini_b        0.90  0.27
o3_mini_c        0.98  0.01
o3_mini_d        0.98  0.01
random           0.00  0.00

In [17]:
grouped = df[df.grid_seed < 100].groupby('method_name')['reward'].agg(['mean', 'std', 'count'])
grouped['ci95'] = 1.96 * grouped['std'] / np.sqrt(grouped['count'])
grouped[['mean', 'ci95']].round(2)

                 mean  ci95
method_name
claude           0.78  0.08
claude_b         0.91  0.05
claude_c         0.91  0.05
deepseek         0.94  0.04
deepseek_b       0.87  0.06
gemini_25_pro    0.68  0.09
gemini_25_pro_b  0.79  0.08
gemini_25_pro_c  0.91  0.05
gemini_25_pro_d  0.00  0.00
gpt_4o           0.00  0.00
gpt_4o_b         0.00  0.00
greedy           0.98  0.00
o1               0.97  0.00
o1_b             0.97  0.00
o1_c             0.00  0.00
o3_mini          0.78  0.08
o3_mini_b        0.90  0.05
o3_mini_c        0.98  0.00
o3_mini_d        0.98  0.00
random           0.00  0.00

In [18]:
input_tokens = 843 + 2853 + 3292 + 3326
output_tokens = 2765 + 3562 + 4217 + 5881

In [19]:
(input_tokens * (1.1 / 1e6) + output_tokens * (4.4 / 1e6))

0.0836154